// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reading_Room.Data;

#nullable disable

namespace Reading_Room.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029072240_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Reading_Room.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatronName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Start", "End");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(2025, 10, 27, 9, 22, 38, 362, DateTimeKind.Utc).AddTicks(187),
                            PatronName = "Alice",
                            RoomId = 1,
                            Start = new DateTime(2025, 10, 27, 7, 22, 38, 361, DateTimeKind.Utc).AddTicks(9799),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            End = new DateTime(2025, 10, 28, 10, 22, 38, 362, DateTimeKind.Utc).AddTicks(532),
                            PatronName = "Bob",
                            RoomId = 1,
                            Start = new DateTime(2025, 10, 28, 7, 22, 38, 362, DateTimeKind.Utc).AddTicks(530),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Reading_Room.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 6,
                            Name = "Room A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10,
                            Name = "Room B"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            Name = "Room C"
                        });
                });

            modelBuilder.Entity("Reading_Room.Models.Reservation", b =>
                {
                    b.HasOne("Reading_Room.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Reading_Room.Models.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
